### PR TITLE
Display, lvgl and related

### PR DESCRIPTION
**Pull request by persello**
Hello, I started working on the display part. I still need to change the default driver to use the AXP192 pins, but for now I integrated lvgl as a frozen module and I expanded the partition table to fill all the 16MB. 4MB are reserved for factory app.

I also added an utility function to activate the vibration motor from the M5Stack class. I don't think I'll be able to write the touchscreen driver, I already tried to submit a request for a datasheet/sample code but the touchscreen panel producer's requests form on their website seems broken.

I found an Arduino library that should work with that panel: [FT6X36](https://github.com/strange-v/FT6X36). Right now I'm more interested in getting the display work before the touchscreen. I think the panel on the Core 2 is an FT6336, correct me if I'm wrong.

### CODE REVIEW

**Comment by persello** [comment]
(After creating this draft I see there are some problems with Travis CI. I think they are related to the lv_bindings submodule)

**Comment by imliubo** [comment]
Hi @persello ,
Thanks for your contribution 😀.

> I don't think I'll be able to write the touchscreen driver, I already tried to submit a request for a datasheet/sample code but the touchscreen panel producer's requests form on their website seems broken.

The function of the touch chip is customized, and the coordinates can be read by simple I2C communication. I will complete this part of the work.

>I think the panel on the Core 2 is an FT6336, correct me if I'm wrong.

Yes, it's FT6336U. The manufacturer has disabled some functions, and currently only supports single-point feedback. In addition, the three virtual buttons below are also judged by the coordinates of the touch position of the FT6336U.

Finally, it seems that the code style check failed. I think we can follow the same code style as the original micropython repository, so please use the ``tools/codeformat.py`` script to check first😜. If **CI** passed, I will merge your excellent contribution.

**Comment by persello** [comment]
Regarding the code style check, I saw it on the last build and I'll check out the details as soon as I can, but before I had different problems due to the `lv_bindings` submodules not being cloned.

In relation to the display driver, I'd like to start from the ILI9431 hybrid driver, but I'm having some issues on getting the C files it depends on compiled correctly. As of now, without a driver, the library has almost no use. Eventually we could use a pure micropython driver, but I think it might be too slow.

The hybrid driver could work in my opinion, since the pins connected to the AXP are only used in the micropython initialization (and not used in the C part of the driver).

**Comment by imliubo** [comment]
> Regarding the code style check, I saw it on the last build and I'll check out the details as soon as I can.

I took a look, and the main cause of CI failure was this automatically generated file ``ports/esp32/lextab.py``. I looked at it and it seemed that we could ignore this file. What do you think?

>In relation to the display driver, I'd like to start from the ILI9431 hybrid driver, but I'm having some issues on getting the C files it depends on compiled correctly.

Write the display driver from the C code, it would be a little difficult, did you write this before?

>Eventually we could use a pure micropython driver, but I think it might be too slow.

I think we can use the ili934X pure micropython driver from the ``lv_binding`` repository at frist.

>The hybrid driver could work in my opinion, since the pins connected to the AXP are only used in the micropython initialization (and not used in the C part of the driver).

The LCD ``power`` ``RST`` ``BL`` pins is connected the AXP chip, so only after power the ili9341 we can initialization the LCD to work.

**Comment by persello** [comment]
I agree with the fact that we could start with the pure micropython driver.
This afternoon I'll give it a try.

> Write the display driver from the C code, it would be a little difficult, did you write this before?

I think the ILI9341 hybrid driver would work without modifying the C part. The main problem for me is getting the display driver C modules to compile. I'm not really good with makefiles in large projects such as these and I think this will require me to study the lv_micropython firmware repo and how they configured the ESP32 part.

If I can get the C files in `lib/lv_bindings/driver/esp32` (hope I got the path correctly, I'm on my phone) to compile, I think the job is more than half done: after editing the display initialization to use the AXP pins instead of the ESP ones, we could already have something to work on.

The initialization sequence could be different, but I think it's trivial to make such a change. I really really hope it's as simple as I think, but I often end up being wrong on this.

Answering your question, I once wrote a simple driver for a larger ILI display in ESP-IDF, but right now I have little to no ideas on how to expose C functions to micropython.

**EDIT**: I noticed that even a pure micropython driver requires to compile the espidf module for allocating DMA memory. At this point, I think I could directly aim to an hybrid driver.

> I took a look, and the main cause of CI failure was this automatically generated file ports/esp32/lextab.py. I looked at it and it seemed that we could ignore this file. What do you think?

Seems to be an automatically generated file. I don't know what generates it and how frequently. In my opinion, a better solution would be to whitelist this file in some way (if possible).

**Comment by persello** [comment]
Houston, we have a (reversed) hybrid driver! 🥳

image

**Comment by persello** [comment]
The driver works (also, not reversed anymore), but I had some linking issues with the generic ESP32 board. Specifying `BOARD=M5STACK_CORE2` works fine, so I decided to change it in the Travis configuration file. Using a generic board, the linker fails because of some dependecies such as mbedtls, and I didn't understand where this problem comes from. I thought to edit `travis.yml` since this repository is focused on the Core 2 port, but if you feel this project should successfully build for a generic board, the changes related to what I described are in the commit f3630c7.

Talking about the files that make the code formatting workflow to fail, I can confirm that they are generated very frequently (I suspect after every build with changes to python modules). I think it would be better to exclude them from the check.

Regarding the driver, you can test it with this script:
```python
from m5stack import M5Stack
import lvgl as lv
import lvesp32
from axpili9342 import *

lv.init()
ms = M5Stack()
disp = ili9342(ms)

# Create a screen with a button and a label

scr = lv.obj()
btn = lv.btn(scr)
btn.align(lv.scr_act(), lv.ALIGN.CENTER, 0, 0)
label = lv.label(btn)
label.set_text("Hello World!")

# Load the screen

lv.scr_load(scr)
```

**Comment by imliubo** [comment]
Wow, you did a lot of great work and it looks great! I will merge it right away, thank you very much!😉

**Pull request merged**
